### ISSUE TITLE
Cannot get serverinfo for Keycloak 24.0.4

### ISSUE THREAD

**Issue by VladVKozlov** [silentpartnersoftware/Keycloak.Net#41] opened 2024-05-08 20:04 UTC
I get the exception after migrating from Keycloak 23.0.4 to 24.0.4. With 23.0.4 the below code works fine.
Image quay.io/keycloak/keycloak:24.0.4

.Net App Code:
```
private readonly KeycloakClient _client = new KeycloakClient(
  config["Keycloak:KeycloakUrl"], 
  config["Keycloak:AdminClientUserName"],
  config["Keycloak:AdminClientPassword"]
);
private readonly string _realmName = config["Keycloak:RealmName"] ?? throw new InvalidOperationException();

await _client.GetServerInfoAsync(_realmName); // Here is the exception thrown
```

Exception:
```
Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET http://ds.keycloak:8080/admin/serverinfo/
 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'componentTypes['org.keycloak.keys.KeyProvider'][4].properties[3].defaultValue', line 1, position 157256.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Flurl.Http.Configuration.NewtonsoftJsonSerializer.Deserialize[T](Stream stream)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   --- End of inner exception stack trace ---
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlResponse.GetJsonAsync[T]()
   at Flurl.Http.ResponseExtensions.ReceiveJson[T](Task`1 response)
   at Keycloak.Net.KeycloakClient.GetServerInfoAsync(String realm, CancellationToken cancellationToken)
...
```

**Comment by sps-campbellwray** [comment] 2024-05-09 16:49
Hi @VladVKozlov,

Thanks for submitting an issue. 

After a bit of investigation it looks like the structure of the object returned by the `serverinfo` endpoint changed in 24.0.4

23.0.4:
![image](https://github.com/silentpartnersoftware/Keycloak.Net/assets/67340768/79ec4d6a-aa19-4248-9d4f-b54bbe5d9182)

24.0.4:
![image](https://github.com/silentpartnersoftware/Keycloak.Net/assets/67340768/a4b1efe4-1108-485f-a356-2469470d9755)

Specifically the `defaultValue` went from being a single value, to being a list.

I'm not sure if this is a regression on the Keycloak side, or if they are now allowing for multiple default values for this property. I have submitted [an issue to the Keycloak repo](https://github.com/keycloak/keycloak/issues/29426), and will see what comes of it.

If this is intentional then we can change the type of `ConfigProperty.DefaultValue` from a `string` to an `object`, but I don't want to do this until I know whether this change is necessary.

In the meantime, if this is blocking you I would suggest that you checkout our repo locally and build it with the type of the `DefaultValue` property changed to `object`.

Thanks,
Campbell

**Comment by sps-campbellwray** [comment] 2024-05-22 13:11
@VladVKozlov this has been fixed in Keycloak and should work again in a future release. 

I am going to close this ticket since there is nothing to change in Keycloak.Net. Please be aware that this fix has not been back-ported to v24 (this could change in the future), so I'm not sure when it will be released.

Link to the PR:
https://github.com/keycloak/keycloak/pull/29747

**Closed by sps-campbellwray** 2024-05-22 13:11 UTC
